n = input('Digite algo: ')
print('Você digitou:', n)
print('O tipo dele é', type(n))
print('São somente espaços? ', n.isspace())
print('Ele é númerico? ', n.isnumeric())
print('Ele é alfabético? ', n.isalpha())
print('Ele é alfanumérico? ', n.isalnum())
print('Ele está totalmente em maiúsculo? ', n.isupper())
print('Ele está totalmente em minúsculo? ', n.islower())
print('Ele está capitalizado? ', n.istitle())
print('Obrigado por participar!')
